export const FETCH_HOME_PAGE_DATA = "ihi/home/FETCH_HOME_PAGE_DATA";
export const FETCH_HOME_PAGE_DATA_SUCCESS =
  "ihi/home/FETCH_HOME_PAGE_DATA_SUCCESS";
export const FETCH_HOME_PAGE_DATA_FAILED =
  "ihi/home/FETCH_HOME_PAGE_DATA_FAILED";
