export const FETCH_ALL_ITINERARY_LIST =
  "ihi/itinerary/FETCH_ALL_ITINERARY_LIST";
export const FETCH_ALL_ITINERARY_LIST_SUCCESS =
  "ihi/itinerary/FETCH_ALL_ITINERARY_LIST_SUCCESS";
export const FETCH_ALL_ITINERARY_LIST_FAILED =
  "ihi/itinerary/FETCH_ALL_ITINERARY_LIST_FAILED";

export const FETCH_ITINENARY_DETAILS = "ihi/itinerary/FETCH_ITINENARY_DETAILS";
export const FETCH_ITINENARY_DETAILS_SUCCESS =
  "ihi/itinerary/FETCH_ITINENARY_DETAILS_SUCCESS";
export const FETCH_ITINENARY_DETAILS_FAILED =
  "ihi/itinerary/FETCH_ITINENARY_DETAILS_FAILED";

export const SUBMIT_ITINERARY_REVIEW = "ihi/itinerary/SUBMIT_ITINERARY_REVIEW";
export const SUBMIT_ITINERARY_REVIEW_SUCCESS =
  "ihi/itinerary/SUBMIT_ITINERARY_REVIEW_SUCCESS";
export const SUBMIT_ITINERARY_REVIEW_FAILED =
  "ihi/itinerary/SUBMIT_ITINERARY_REVIEW_FAILED";

export const SEARCH_ITINERARY = "ihi/itinerary/SEARCH_ITINERARY";
export const SEARCH_ITINERARY_SUCCESS =
  "ihi/itinerary/SEARCH_ITINERARY_SUCCESS";
export const SEARCH_ITINERARY_FAILED = "ihi/itinerary/SEARCH_ITINERARY_FAILED";

export const SEARCH_ITINERARY_FILTERS_RESULTS_SUCCESS =
  "ihi/itinerary/SEARCH_ITINERARY_FILTERS_RESULTS_SUCCESS";

  export const SEARCH_ITINERARY_FILTERS_RESULTS_FAILED =
  "ihi/itinerary/SEARCH_ITINERARY_FILTERS_RESULTS_FAILED";
