export const FETCH_BLOGS_LIST = "ihi/blogs/FETCH_BLOGS_LIST";
export const FETCH_BLOGS_LIST_SUCCESS = "ihi/blogs/FETCH_BLOGS_LIST_SUCCESS";
export const FETCH_BLOGS_LIST_FAILED = "ihi/blogs/FETCH_BLOGS_LIST_FAILED";

export const FETCH_BLOG_DETAILS = "ihi/blogs/FETCH_BLOG_DETAILS";
export const FETCH_BLOG_DETAILS_SUCCESS =
  "ihi/blogs/FETCH_BLOG_DETAILS_SUCCESS";
export const FETCH_BLOG_DETAILS_FAILED = "ihi/blogs/FETCH_BLOGS_LIST_FAILED";

export const SUBMIT_BLOG_REVIEW = "ihi/blogs/SUBMIT_BLOG_REVIEW";
export const SUBMIT_BLOG_REVIEW_SUCCESS =
  "ihi/blogs/SUBMIT_BLOG_REVIEW_SUCCESS";
export const SUBMIT_BLOG_REVIEW_FAILED =
  "ihi/blogs/SUBMIT_ITINERARY_REVIEW_FAILED";
