export const SUBMIT_QUERY_FORM = "ihi/global/SUBMIT_QUERY_FORM";
export const SUBMIT_QUERY_FORM_SUCCESS = "ihi/global/SUBMIT_QUERY_FORM_SUCCESS";
export const SUBMIT_QUERY_FORM_FAILED = "ihi/global/SUBMIT_QUERY_FORM_FAILED";

export const FETCH_FOOTER_DATA = "ihi/global/FETCH_FOOTER_DATA";
export const FETCH_FOOTER_DATA_SUCCESS = "ihi/global/FETCH_FOOTER_DATA_SUCCESS";
export const FETCH_FOOTER_DATA_FAILED = "ihi/global/FETCH_FOOTER_DATA_FAILED";

export const FETCH_CONTACT_DETAILS = "ihi/global/FETCH_CONTACT_DETAILS";
export const FETCH_CONTACT_DETAILS_SUCCESS =
  "ihi/global/FETCH_CONTACT_DETAILS_SUCCESS";
export const FETCH_CONTACT_DETAILS_FAILED =
  "ihi/global/FETCH_CONTACT_DETAILS_FAILED";

export const FETCH_CATEGORIES = "ihi/global/FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "ihi/global/FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILED = "ihi/global/FETCH_CATEGORIES_FAILED";

export const FETCH_LOCATIONS = "ihi/global/FETCH_LOCATIONS";
export const FETCH_LOCATIONS_SUCCESS = "ihi/global/FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAILED = "ihi/global/FETCH_LOCATIONS_FAILED";

